import type { SampleGrantAward, SampleOpportunity } from "@/lib/public-samples";

/** Illustrative public teasers used when Supabase is not configured yet.
 * Every row is an example (not a live SAM.gov notice). Agencies and NAICS
 * are deliberately mixed so the empty-scaffold preview still looks diverse. */
export const FALLBACK_SAMPLE_OPPORTUNITIES: SampleOpportunity[] = [
  {
    title: "Janitorial Services for the Atlanta Federal Center",
    agency: "GENERAL SERVICES ADMINISTRATION.PUBLIC BUILDINGS SERVICE.PBS REGION 4",
    naicsCode: "561720",
    responseDeadline: "2026-10-15T20:00:00.000Z",
    noticeId: "BK-EX-GSA-561720",
    noticeUrl: null,
    setAsideType: "Total Small Business Set-Aside",
    postedAt: "2026-08-20T14:00:00.000Z",
    placeOfPerformanceState: "GA",
    isExample: true,
  },
  {
    title: "Grounds Maintenance — National Cemetery of the Alleghenies",
    agency: "DEPT OF VETERANS AFFAIRS.NATIONAL CEMETERY ADMINISTRATION",
    naicsCode: "561730",
    responseDeadline: "2026-09-02T21:00:00.000Z",
    noticeId: "BK-EX-VA-561730",
    noticeUrl: null,
    setAsideType: "Service-Disabled Veteran-Owned Small Business Set-Aside",
    postedAt: "2026-07-18T15:00:00.000Z",
    placeOfPerformanceState: "PA",
    isExample: true,
  },
  {
    title: "Armed Guard Services at Fort Moore Access Control Points",
    agency: "DEPT OF DEFENSE.DEPT OF THE ARMY.US ARMY ACC",
    naicsCode: "561612",
    responseDeadline: "2026-11-03T18:00:00.000Z",
    noticeId: "BK-EX-ARMY-561612",
    noticeUrl: null,
    setAsideType: "8(a) Set-Aside",
    postedAt: "2026-08-28T13:00:00.000Z",
    placeOfPerformanceState: "GA",
    isExample: true,
  },
  {
    title: "Base Operations / Facilities Support — Kennedy Space Center",
    agency: "NATIONAL AERONAUTICS AND SPACE ADMINISTRATION.NASA KENNEDY SPACE CENTER",
    naicsCode: "561210",
    responseDeadline: "2026-10-30T17:00:00.000Z",
    noticeId: "BK-EX-NASA-561210",
    noticeUrl: null,
    setAsideType: "Full and Open",
    postedAt: "2026-08-12T16:00:00.000Z",
    placeOfPerformanceState: "FL",
    isExample: true,
  },
  {
    title: "Custodial Services for Processing & Distribution Center",
    agency: "UNITED STATES POSTAL SERVICE.SUPPLY MANAGEMENT",
    naicsCode: "561720",
    responseDeadline: "2026-08-01T22:00:00.000Z",
    noticeId: "BK-EX-USPS-561720",
    noticeUrl: null,
    setAsideType: "HUBZone Set-Aside",
    postedAt: "2026-06-22T12:00:00.000Z",
    placeOfPerformanceState: "TX",
    isExample: true,
  },
  {
    title: "Pest Control Services — VA Medical Center Campus",
    agency: "DEPT OF VETERANS AFFAIRS.VETERANS HEALTH ADMINISTRATION",
    naicsCode: "561710",
    responseDeadline: "2026-12-01T20:00:00.000Z",
    noticeId: "BK-EX-VA-561710",
    noticeUrl: null,
    setAsideType: "Woman-Owned Small Business Set-Aside",
    postedAt: "2026-09-01T14:30:00.000Z",
    placeOfPerformanceState: "OH",
    isExample: true,
  },
  {
    title: "Unarmed Security Guard Services — FEMA Warehouse",
    agency: "DEPT OF HOMELAND SECURITY.FEDERAL EMERGENCY MANAGEMENT AGENCY",
    naicsCode: "561612",
    responseDeadline: "2026-07-20T19:00:00.000Z",
    noticeId: "BK-EX-FEMA-561612",
    noticeUrl: null,
    setAsideType: "Total Small Business Set-Aside",
    postedAt: "2026-06-10T11:00:00.000Z",
    placeOfPerformanceState: "MD",
    isExample: true,
  },
  {
    title: "Landscaping and Irrigation Maintenance — National Forest Compounds",
    agency: "DEPT OF AGRICULTURE.FOREST SERVICE.USDA FOREST SERVICE",
    naicsCode: "561730",
    responseDeadline: "2026-11-18T21:00:00.000Z",
    noticeId: "BK-EX-USFS-561730",
    noticeUrl: null,
    setAsideType: "Total Small Business Set-Aside",
    postedAt: "2026-08-30T13:45:00.000Z",
    placeOfPerformanceState: "OR",
    isExample: true,
  },
];

export const FALLBACK_SAMPLE_GRANTS: SampleGrantAward[] = [
  {
    recipientName: "City of Columbus Board of Education",
    awardingAgency: "Department of Agriculture",
    state: "GA",
    amount: 1850000,
    programNumber: "10.766",
    awardId: "BK-EX-GRANT-10766",
    awardNumber: "CF-26-0142",
    startDate: "2026-07-01",
  },
  {
    recipientName: "Housing Authority of the City of Pittsburgh",
    awardingAgency: "Department of Housing and Urban Development",
    state: "PA",
    amount: 4200000,
    programNumber: "14.872",
    awardId: "BK-EX-GRANT-14872",
    awardNumber: "PA26-P001-001",
    startDate: "2026-06-15",
  },
  {
    recipientName: "Ohio Development Services Agency",
    awardingAgency: "Department of Energy",
    state: "OH",
    amount: 960000,
    programNumber: "81.042",
    awardId: "BK-EX-GRANT-81042",
    awardNumber: "EE0009xxx",
    startDate: "2026-05-20",
  },
];
